---
name: python checks

on: push

jobs:
  typers:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        typer:
          - mypy
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: ./.github/workflows/setup_poetry@feat/use_github_reusable_workflows

      - name: Type check (${{ matrix.typer }})
        run: poetry run ${{ matrix.typer }} aoc2020

  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - uses: ./.github/workflows/setup_poetry@feat/use_github_reusable_workflows

      - name: Python tests
        run: poetry run pytest -v
